services:
  db:
    image: mysql:8.0
    container_name: gagallapar_db
    restart: always
    environment:
      MYSQL_DATABASE: db_tugas_akhir_2026
      MYSQL_ROOT_PASSWORD: zaki-kik-gtg-123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./App/BE
      dockerfile: Dockerfile.be
    container_name: gagallapar_be
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./App/FE
      dockerfile: Dockerfile.fe
    container_name: gagallapar_fe
    restart: always
    ports:
      - "5173:5173"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: gagallapar_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge